<!DOCTYPE html>
<html>

<head>
    {{$include 'commons/head'}}
</head>

<body>
    <div id="page">
        <p>This has been generated by <b>mustacher:src_to_dest</b> task</p>
    </div>
    {{$livereload 1337}}
</body>

</html>